CONTAINER lobject
{
	NAME lobject;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL L_OBJECT_HEIGHT { UNIT METER; MIN 0.0; STEP 0.1;}
		REAL L_OBJECT_WIDTH { UNIT METER; MIN 0.0; STEP 0.1; }
		REAL L_OBJECT_DEPTH { UNIT METER; MIN 0.0; STEP 0.1;}
		REAL L_OBJECT_CURVE_OFFSET { MIN 0.0; STEP 0.1; }
		REAL L_OBJECT_WIDTH_SEGMENTS { MIN 0; STEP 1;}
	}

	GROUP L_OBJECT_PHONG_TAB
	{
		BOOL L_OBJECT_ENABLE_PHONG_TAG { }
		BOOL L_OBJECT_ANGLE_LIMIT { }
		REAL L_OBJECT_PHONG_ANGLE { UNIT DEGREE; MIN 0; MAX 180; STEP 1; }
	}

}
