CONTAINER olobject
{
	NAME olobject;
	INCLUDE Obase;

	GROUP ID_OBJECTPROPERTIES
	{
		REAL HEIGHT_0 { UNIT METER; MIN 0; STEP 0.1;}
		REAL HEIGHT_1 { UNIT METER; MIN 0; STEP 0.1;}
		SEPARATOR { }
		REAL WIDTH { UNIT METER; MIN 0; STEP 0.1;}
		SEPARATOR { }
		REAL DEPTH_0 { UNIT METER; MIN 0; STEP 0.1;}
		REAL DEPTH_1 { UNIT METER; MIN 0; STEP 0.1;}
		SEPARATOR { }
		REAL CURVE_OFFSET_0 { UNIT METER; MIN 0; STEP 0.1;}
		REAL CURVE_OFFSET_1 { UNIT METER; MIN 0; STEP 0.1;}
		REAL CURVE_OFFSET_2 { UNIT METER; MIN 0; STEP 0.1;}
		SEPARATOR { }
		LONG WIDTH_SEGMENTS { MIN 0; STEP 1;}
	}
}
